### ISSUE TITLE
ABI Stable API - milestones

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#2]
We've been making some progress on the ABI stable API (will provide an update in WG  meeting https://github.com/nodejs/api/issues/22)

This is to capture the current view of some of the major milestones for PoC:
- [x] First example running
- [x] All NaN examples running
- [x] Module lifecycle methods
- [ ] Robust Object life-cycle handling
- [x] Create/GetData methods for all primitive javascript types
- [ ] Complete conversion functions for primitive types
- [ ] Exception Handling methods complete
- [ ] Error handling methods complete
- [ ] Buffer methods complete
- [ ] Version management methods complete
- [x] Level down running
- [x] nanomessage running
- [ ] module 3 running
- [ ] leveldown performance analysis
- [ ] module 3 performance analysis
- [ ] nanomessage performance analysis
- [ ] understand impact of multi-isolate modules, e.g. `webworker-threads`
- [ ] Test suite complete
- [ ] Safety/Usability Analysis complete
- Validate API copes with other implementations:
  - [x] Port back to 0.10.X and/or
  - [ ] Port back to 0.12.X and/or
  - [x] Port to NodeChakra and/or
  - [ ] Port to SpiderNode
  - [ ] DukTape?
- [ ] Fill out rest of C API
- [ ] NaN/C++ wrapper feasibility analysis complete
- [ ] Make AsyncWorkers ABI stable.

**Comment by mhdawson** [comment]
We are long past this stage, closing. Please let us know if you think that was not the right thing to do.
