### ISSUE TITLE
Burn down list of issues raised by module owners

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#281]
Community reported issues:
- [ ] Microtask queue interaction with N-API (https://github.com/nodejs/abi-stable-node/issues/279)
- [ ] Callback to js from native threads (https://github.com/nodejs/abi-stable-node/issues/279#issuecomment-336061708)
- [x] 3x perf overhead in napi version of native-hdr-histogram (https://github.com/nodejs/node-addon-api/issues/102) (@digitalinfinity)
- [x] Convert.js not updating dependencies in binding.gyp (https://github.com/nodejs/node-addon-api/issues/98) (@sampsongao)
- [x] Make Buffer extend Uint8Array (https://github.com/nodejs/node-addon-api/issues/109) (@sampsongao)
- [x] Enforce HandleScope semantics more strictly (https://github.com/nodejs/node/issues/16175)
- [ ] Resolve promises asynchronously without `napi_create_async_work` (https://github.com/nodejs/node/issues/15604)

**Comment by digitalinfinity** [comment]
I'll edit the issue to include the links to the issues that are being tracked by this meta-issue

**Comment by mhdawson** [comment]
https://github.com/nodejs/abi-stable-node/issues/279

**Comment by digitalinfinity** [comment]
@mhdawson I've added a few issues here- feel free to update the issue to add any I might have missed (and I'll add more to this list as they come in)

**Comment by mhdawson** [comment]
@digitalinfinity thanks !

**Comment by YafimK** [comment]
- [ ] create custom env - when creating an async worker, you may want to manipulate env to be with another isolate. A bit closer to Node ENV.

**Comment by digitalinfinity** [comment]
Thanks @YafimK - can you create a separate issue in nodejs/node with more details on what change you'd like to see, perhaps with the use case- I can then update the above list and link to that issue.

**Comment by digitalinfinity** [comment]
For node-native-histogram, I've determined that the benchmark is not doing a significant amount of work, so its effectively just measuring the difference between napi_call_function and nan's function call API. Given that, I don't think we have to necessarily address this immediately since in most benchmarks where the benchmark does non-trivial work, the overhead difference would be less significant and so I'll check this off our list. However, I'll continue to look at whether there are more clever things we can do to reduce the absolute difference in overheads but napi_call_function will always have greater overhead since it's a more general API than nan.

**Comment by gabrielschulhof** [comment]
https://github.com/MayhemYDG/iltorb/tree/napi documents a slight memory leak wrt. V8 bindings.

**Comment by gabrielschulhof** [comment]
https://github.com/MayhemYDG/iltorb/pull/70#issuecomment-397127385

**Comment by NickNaso** [comment]
Hi everyone I want report this issue https://github.com/kelektiv/node.bcrypt.js/issues/709 developers are starting use ative addons in `worker_threads` so they need to refactor to implement a context aware addon.

**Comment by gabrielschulhof** [comment]
We discussed a possible solution to the accumulation of native finalizers during a tight loop that creates wrapped objects here:

https://github.com/nodejs/node-addon-api/issues/1140

**Comment by legendecas** [comment]
Team tracking list moved to https://github.com/orgs/nodejs/projects/11.
