### ISSUE TITLE
Potential conference talks and workshops

### ISSUE THREAD

**Issue by jschlight** [nodejs/abi-stable-node#292]
This is a location to post potential talks and workshops for upcoming conferences.

Two conferences have been identified:

- [Node Summit](http://www.nodesummit.com) San Francisco, US - July 23-25, 2018
- [JS Interactive](https://events.linuxfoundation.org/events/js-interactive-2018/) - Vancouver, Canada - October 10-12, 2018 (CFP Close: Friday, April 20, 2018, 11:59 PST)

Potential talks that have been discussed are:

1) A deep dive into node-addon-api, the new NAN !
2) Using N-API with pre-gyp (with Jim obviously)
3) N-API porting workshop,bring your module, lets port ! (on Day zero ?)
4) Nicola's talk on porting Bcrypt
5) N-API in the wild, looking at production usage to date 
6) N-API no longer experimental, porting your module step by step.

**Comment by NickNaso** [comment]
I think that could be interesting to be at this conference:

[NodeConf EU](http://www.nodeconf.eu/) - 4 - 7* November 2018 | Lyrath Estate, Kilkenny, Ireland (CFP Close: Friday 1st June 2018)

**Comment by mhdawson** [comment]
Agreed, NodeConfEU is also a good one to target.

**Comment by mhdawson** [comment]
Actions:

* Michael/Arunesh put together outline/submission for N-API update. 
  * include -  N-API in the wild, looking at production usage to date
* Jim - N-API porting workshop,bring your module, lets port !   
  * N-API no longer experimental, porting your module step by step. - cover in workshop
* Nicola to submit talk on porting Bcrypt to Node interactive
* Jim to do outline for Using N-API with pre-gyp (Jim at JS Interactive, Nicola/Michael JSConfEU, Node Summit TBD).
* Gabriel to submitted - Implementing N-API on JerryScript -  JS Interactive and Node Summit
* Michael write up outline - A deep dive into node-addon-api, the new NAN !

**Comment by jschlight** [comment]
> This is proposed outline 

# An N-API Workshop

## Abstract

Ready to get your hands dirty with N-API, Node's new ABI-stable native add-on API? Don't miss this workshop. Whether you're maintaining a NAN module, looking to start a new add-on using N-API, or are interested in porting existing native add-ons to N-API, we're here to get you started right. After a brief introduction you'll have the chance to work through a tutorial or bring your project and N-API experts will be available to help you through any issues. You'll leave with a solid understanding N-API and the tools available to help you best succeed. 

## Objectives

- Help existing and first-time native module maintainers to get started with N-API

- Orientation to best practices

- Offer hands-on assistance during the workshop for projects of importance to the participants

- Offer tips, tools, and resources participants can use after the workshop

- Solicit suggestions and ideas to improve N-API and it's supporting ecosystem

## Concept

The idea would be to offer some opening remarks about N-API in general. We might then poll the participants to determine how many are brand new to native modules and how many are attempting to port an existing module to N-API. It would be good to know how many have brought a specific project to work on and how many are there to get a start with N-API. 

Based on the feedback, we could then split up the group and the facilitators could then concentrate on a specific group, but still be available for other questions.

The second part of the workshop would comprise of working directly with participants  

## Topics

### Part 1 - Brief introductory remarks

- Poll participants about interest in today's workshop

- Benefits of N-API — ABI stable, works across JavaScript engines

- Available tools and online tutorials

### Part 2 - Hands-on assistance

- One group working through the initial tutorials

- The other group working through migrating an existing module

### Part 3 - Wrap up

- A verbal evaluation of the workshop, how might it be improved?

- Suggestions for improving N-API in general?

- Questions?

**Comment by jschlight** [comment]
> This is proposed outline 

# Enhancing an N-API Module with node-pre-gyp

## Abstract

Add significant value to your Node native add-on by offering your users pre-built binaries they can download in a flash. This talk will walk you though the necessary steps to add `node-pre-gyp` support to your N-API native module. This talk will be of particular interest to native add-on developers who are adopting N-API as it will describe in detail the `node-pre-gyp` configuration changes required to support N-API. Participants will leave with a solid understanding of how `node-pre-gyp` works, especially in the N-API environment. 

## Objectives

- Give participants a good overview and understanding of the reson for adopting node-pre-gyp and the steps required to achieve it

- Offer tips, tools, and resources participants can use after the presentation

## Topics

- Purpose of node-pre-gyp — Ability to upload pre-built binaries, N-API binaries last indefinitely, benefit to users

- Prerequisites — Routine N-API build requirements, an S3 account with upload permissions

- Special considerations for N-API vs. NAN — N-API versioning, 

- Configuration file differences - package.json, binding.gyp

- Other upload options beyond S3

- Demo

- Questions?

**Comment by jschlight** [comment]
> This is proposed outline 

# Migration of a Native Module to N-API

## Abstract

Retool your NAN module for N-API, Node's new JavaScript engine agnostic, ABI-stable native add-on API. The N-API add-on you build today will run without modification on future versions of Node. This talk walks you through the migration process, step-by-step, so you can successfully convert your NAN module to N-API. We'll cover the conceptual and practical differences between NAN and N-API, the available conversion script, and any addition steps required for complete your N-API migration. 

## Objectives

- Describe the steps required to port a module from NAN to N-API

- Offer tips, tools, and resources participants can use after the presentation

## Topics

- Benefits of N-API — ABI stable, works across JavaScript engines

- Conceptual differences between NAN and N-API

- Practical differences between NAN and N-API

- The node-addon-api conversion script

- Additional cleanup required

- Demo

- Questions?

**Comment by aruneshchandra** [comment]
# N-API:The Next Generation Node API is ready!

## Abstract
Native module ecosystem in Node.js is quite fragile and presents several challenges in the rapid growth of Node.js. Due to lack of ABI stability in Node.js these modules are tied to a specific version of V8/Node.js and creates friction in upgrading to newer Node.js versions in production deployments. And also Native module maintainers have to incur maintenance cost to cope with the fast pace of changes in the v8 APIs. N-API is the next generation ABI stable Node.js API for native modules aiming to solve these problems. This talk is going to provide a progress update of this community project and also discuss the roadmap and how to get involved.

**Comment by mhdawson** [comment]
How about tweaking to be:

N-API: The Next Generation Node API is ready!

Abstract
The Native module ecosystem for Node.js is an important factor in the rapid growth of Node.js. The N-API  is now a **supported feature** and is designed to provide ABI stability across Node.js releases.  This will reduce friction in upgrading to newer Node.js versions in production deployments. In addition, it will reduce the maintenance cost that module maintainers previously had to take on due to the fast pace of changes in the v8 APIs. This talk will provide a progress update on this community project, the roadmap,  and why now is the right time to get involved.
.

**Comment by mhdawson** [comment]
And the abstract I had the action to create.

Building Next Generation Add-on modules for Node.js

You may have heard that the N-API is now a **supported** Node.js feature.  N-API provides an ABI stable C based api that you can use directly, however, many developers will want to use the C++ wrapper module - node-addon-api.  As a replacement for the NAN module, node-addon-api provides the easiest way to migrate your existing native addons to use N-API.  This talk will introduce the node-addon-api module, show you how use it with code samples and show you some of the migration tools that are available.  If you are going to be writing or maintaining native addons with Node.js you'll want to jump start your learning process by attending this session.

**Comment by mhdawson** [comment]
Node Summit

- [x] N-API: The Next Generation Node API is ready!   (Arunesh)
- [X] Implementing N-API on JerryScript (Gabriel)
- [x] Building Next Generation Add-on modules for Node.js Michael

- [x] An N-API Workshop (all)

**Comment by mhdawson** [comment]
JS Interative

- [x] N-API: The Next Generation Node API is ready! (Michael)
- [x] Enhancing an N-API Module with node-pre-gyp (Jim)
- [x] Experience porting Bcrypt to N-API (Nikola)
- [x] Implementing N-API on JerryScript (Gabriel)
- [x] Migration of a Native Module to N-API (Jim)
 
- [x] An N-API Workshop (All)

**Comment by mhdawson** [comment]
NodeConfEU

- [x] N-API: The Next Generation Node API is ready! (Michael)
- [x] Enhancing an N-API Module with node-pre-gyp (Jim)
- [x] Experience porting Bcrypt to N-API (Nikola)
- [x] Implementing N-API on JerryScript (Gabriel)
- [x] Migration of a Native Module to N-API (Nikola)
 
- [x] An N-API Workshop (Gabriel) (to be there, Michael, Gabriel, Nikola, Jim)

**Comment by mhdawson** [comment]
@nodejs/abi-stable-api, please send bio/email/twitter/linkedin to @jschlight

**Comment by NickNaso** [comment]
Hi everyone today I wrote the abstract for my talk. What do you think? 

## My journey into  N-API

One of the most important feature announced with Node.js 8 was N-API which is aimed at reducing maintenance cost for native add-ons. N-API guarantees the API and ABI compatibility so this means that you don't need to recompile your native add-on if you switch between different versions of Node.js even if you are using different JavaScript engine (V8 or ChackraCore).
This talk will start with the story of how Nicola ported Bcrypt to the new N-API and then used it in production. Along the way Nicola has been ported many native add-ons and he will offer lessons learned, tips and tricks and other insights gained while implementing and porting native add-ons with N-API.
Nicola will show you some statistics about the impact on the performance using N-API and at the end he will illustrate what will be the future developments will like.

**Comment by mhdawson** [comment]
@NickNaso your versions looks good, here is an updated version that I edited a bit. You can either take the suggestions or ignore based on what makes sense to you:

One of the most important features announced with Node.js 8 was N-API which is aimed at reducing the maintenance cost for native add-ons.  N-API guarantees the API and ABI compatibility across versions which means you don't need to recompile your native add-on if you switch between different versions of Node.js, even if you are using different JavaScript engine (V8 or ChackraCore)! This talk will take you on the journey of how Nicola ported Bcrypt to the new N-API and then used it in production. As part of this journey, Nicola ported many native add-ons to N-API. Based on that experience and he will offer lessons learned, tips and tricks and other insights gained. In addition, Nicola will also provide some statistics on the performance differences between N-API and non N-API versions.

**Comment by NickNaso** [comment]
@mhdawson Thank you I like your suggestions. I will provide to submit it to JSInteractive and NodeConf EU.

**Comment by mhdawson** [comment]
Closing submissions done.

**Comment by jschlight** [comment]
I have heard from JS Interactive. Regrettably, none of the three talk proposals I submitted were accepted. 😿

**Comment by NickNaso** [comment]
The same for the my talk proposal.
